"use strict";
exports.__esModule = true;
var express = require("express");
var apiRouter = express.Router();
var gpsRouter_1 = require("./gpsRouter");
var patientsRouter_1 = require("./patientsRouter");
var surgeriesRouter_1 = require("./surgeriesRouter");
var ailmentsRouter_1 = require("./ailmentsRouter");
apiRouter.use('/gps', gpsRouter_1["default"]);
apiRouter.use('/patients', patientsRouter_1["default"]);
apiRouter.use('/surgeries', surgeriesRouter_1["default"]);
apiRouter.use('/ailments', ailmentsRouter_1["default"]);
exports["default"] = apiRouter;
